"""Ajout colonne predicted_label

Revision ID: 04303a18898d
Revises: f7a19f238795
Create Date: 2025-06-18 11:27:26.674476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04303a18898d'
down_revision = 'f7a19f238795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predicted_label', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('predicted_label')

    # ### end Alembic commands ###
