"""Ajout colonne label à Image

Revision ID: 2850e49124bc
Revises: 7873af4bf6d5
Create Date: 2025-06-18 10:46:49.533283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2850e49124bc'
down_revision = '7873af4bf6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
