"""Ajout colonnes features à Image

Revision ID: 7873af4bf6d5
Revises: a6ccd749b658
Create Date: 2025-06-18 10:17:44.107733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7873af4bf6d5'
down_revision = 'a6ccd749b658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_color_r', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_color_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_color_b', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('avg_color_b')
        batch_op.drop_column('avg_color_g')
        batch_op.drop_column('avg_color_r')
        batch_op.drop_column('file_size')
        batch_op.drop_column('height')
        batch_op.drop_column('width')

    # ### end Alembic commands ###
