"""Ajout colonnes histograms, contrast et edges_count

Revision ID: f7a19f238795
Revises: 2850e49124bc
Create Date: 2025-06-18 11:19:51.884103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a19f238795'
down_revision = '2850e49124bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hist_r', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('hist_g', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('hist_b', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('hist_gray', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('contrast', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('edges_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('edges_count')
        batch_op.drop_column('contrast')
        batch_op.drop_column('hist_gray')
        batch_op.drop_column('hist_b')
        batch_op.drop_column('hist_g')
        batch_op.drop_column('hist_r')

    # ### end Alembic commands ###
